import type { Place } from '@/types'

export const MOCK_PLACES: Place[] = [
  {
    id: '1',
    collection_id: 'col-rome',
    name: 'Coliseu',
    description: 'O maior anfiteatro já construído, símbolo do Império Romano. Com capacidade para até 80 mil espectadores, foi palco de gladiadores e espetáculos públicos por séculos.',
    architect: 'Vespasiano / Tito',
    year_built: 80,
    category: 'public',
    latitude: 41.8902,
    longitude: 12.4922,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-rome', city: 'Roma', country: 'Itália', name: 'Roma', description: null, cover_image_url: null, price_brl: 29.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f1', place_id: '1', content: 'Levou apenas 8 anos para ser construído.', order_index: 0 },
      { id: 'f2', place_id: '1', content: 'Tinha um sistema de toldos (velarium) para proteger do sol.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: '2',
    collection_id: 'col-paris',
    name: 'Centro Pompidou',
    description: 'Museu de arte moderna com estrutura exposta em estilo high-tech. Projeto vencedor de concurso internacional em 1977.',
    architect: 'Renzo Piano & Richard Rogers',
    year_built: 1977,
    category: 'museum',
    latitude: 48.8606,
    longitude: 2.3522,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-paris', city: 'Paris', country: 'França', name: 'Paris', description: null, cover_image_url: null, price_brl: 24.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f3', place_id: '2', content: 'Toda a estrutura e instalações são expostas e coloridas por função.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: '3',
    collection_id: 'col-sp',
    name: 'MASP',
    description: 'Museu de Arte de São Paulo Assis Chateaubriand. Projeto de Lina Bo Bardi, suspenso por quatro pilares vermelhos sobre vão livre único.',
    architect: 'Lina Bo Bardi',
    year_built: 1968,
    category: 'museum',
    latitude: -23.5614,
    longitude: -46.6558,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-sp', city: 'São Paulo', country: 'Brasil', name: 'São Paulo', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f4', place_id: '3', content: 'O vão livre de 74m é um dos maiores do mundo para uma estrutura dessa época.', order_index: 0 },
      { id: 'f5', place_id: '3', content: 'Lina Bo Bardi quis que a Avenida Paulista pudesse ser "atravessada" pelo museu.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: '4',
    collection_id: 'col-sydney',
    name: 'Ópera de Sydney',
    description: 'Ícone da arquitetura do século XX com cascas de concreto em forma de velas. Patrimônio Mundial da UNESCO desde 2007.',
    architect: 'Jørn Utzon',
    year_built: 1973,
    category: 'public',
    latitude: -33.8568,
    longitude: 151.2153,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-sydney', city: 'Sydney', country: 'Austrália', name: 'Sydney', description: null, cover_image_url: null, price_brl: 19.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f6', place_id: '4', content: 'O projeto foi aprovado em 1957 a partir de um concurso com 233 propostas.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: '5',
    collection_id: 'col-tokyo',
    name: 'Igreja da Luz',
    description: 'A fenda de luz em forma de cruz na parede de concreto é um dos momentos arquitetônicos mais impactantes do século XX.',
    architect: 'Tadao Ando',
    year_built: 1989,
    category: 'religious',
    latitude: 34.5913,
    longitude: 135.4803,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-tokyo', city: 'Osaka', country: 'Japão', name: 'Japão', description: null, cover_image_url: null, price_brl: 34.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f7', place_id: '5', content: 'Tadao Ando é autodidata — nunca frequentou uma escola de arquitetura.', order_index: 0 },
    ],
    images: [],
  },
]
