import type { Place, Collection } from '@/types'

export const MOCK_COLLECTIONS: Collection[] = [
  { id: 'col-sp', name: 'São Paulo', city: 'São Paulo', country: 'Brazil', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-rome', name: 'Rome', city: 'Rome', country: 'Italy', description: null, cover_image_url: null, price_brl: 29.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-paris', name: 'Paris', city: 'Paris', country: 'France', description: null, cover_image_url: null, price_brl: 24.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-sydney', name: 'Sydney', city: 'Sydney', country: 'Australia', description: null, cover_image_url: null, price_brl: 19.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-tokyo', name: 'Japan', city: 'Osaka', country: 'Japan', description: null, cover_image_url: null, price_brl: 34.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-csh', name: 'Case Study Houses', city: 'Los Angeles', country: 'United States', description: 'The Arts & Architecture Case Study House Program (1945–1966) commissioned leading modernist architects to design and build model homes demonstrating postwar American living.', cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
]

export const MOCK_PLACES: Place[] = [
  {
    id: '1',
    collection_id: 'col-rome',
    name: 'Colosseum',
    description: 'The largest amphitheater ever built, symbol of the Roman Empire. With a capacity of up to 80,000 spectators, it hosted gladiatorial contests and public spectacles for centuries.',
    architect: 'Vespasian / Titus',
    year_built: 80,
    category: 'public',
    latitude: 41.8902,
    longitude: 12.4922,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-rome', city: 'Rome', country: 'Italy', name: 'Rome', description: null, cover_image_url: null, price_brl: 29.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f1', place_id: '1', content: 'It took only 8 years to build.', order_index: 0 },
      { id: 'f2', place_id: '1', content: 'It had a retractable awning system (velarium) to protect spectators from the sun.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: '2',
    collection_id: 'col-paris',
    name: 'Centre Pompidou',
    description: 'Modern art museum with an exposed high-tech structure. Winner of an international competition in 1977, it turned inside-out architecture into a public statement.',
    architect: 'Renzo Piano & Richard Rogers',
    year_built: 1977,
    category: 'museum',
    latitude: 48.8606,
    longitude: 2.3522,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-paris', city: 'Paris', country: 'France', name: 'Paris', description: null, cover_image_url: null, price_brl: 24.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f3', place_id: '2', content: 'All structural and mechanical systems are exposed and color-coded by function.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: '3',
    collection_id: 'col-sp',
    name: 'MASP',
    description: 'Museu de Arte de São Paulo Assis Chateaubriand. Designed by Lina Bo Bardi and suspended by four red pillars over a single 74-meter free span.',
    architect: 'Lina Bo Bardi',
    year_built: 1968,
    category: 'museum',
    latitude: -23.5614,
    longitude: -46.6558,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-sp', city: 'São Paulo', country: 'Brazil', name: 'São Paulo', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f4', place_id: '3', content: 'The 74m free span is one of the largest in the world for a structure of its era.', order_index: 0 },
      { id: 'f5', place_id: '3', content: 'Lina Bo Bardi wanted Avenida Paulista to be "crossed through" the museum beneath it.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: '4',
    collection_id: 'col-sydney',
    name: 'Sydney Opera House',
    description: 'Icon of 20th-century architecture with interlocking concrete shell vaults in the shape of sails. UNESCO World Heritage Site since 2007.',
    architect: 'Jørn Utzon',
    year_built: 1973,
    category: 'public',
    latitude: -33.8568,
    longitude: 151.2153,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-sydney', city: 'Sydney', country: 'Australia', name: 'Sydney', description: null, cover_image_url: null, price_brl: 19.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f6', place_id: '4', content: 'The project was selected in 1957 from a competition with 233 entries.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: '5',
    collection_id: 'col-tokyo',
    name: 'Church of the Light',
    description: 'A cross-shaped slit of light cut into a concrete wall — one of the most powerful architectural moments of the 20th century.',
    architect: 'Tadao Ando',
    year_built: 1989,
    category: 'religious',
    latitude: 34.5913,
    longitude: 135.4803,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-tokyo', city: 'Osaka', country: 'Japan', name: 'Japan', description: null, cover_image_url: null, price_brl: 34.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f7', place_id: '5', content: 'Tadao Ando is self-taught — he never attended an architecture school.', order_index: 0 },
    ],
    images: [],
  },

  // ── Case Study Houses ──────────────────────────────────────────────────────
  {
    id: 'csh-01',
    collection_id: 'col-csh',
    name: 'CSH #1 — Davidson',
    description: 'One of the first realized Case Study Houses. A modest 1,250 sq ft residence in Toluca Lake demonstrating open planning and modern materials for the postwar American family.',
    architect: 'Julius Ralph Davidson',
    year_built: 1948,
    category: 'residential',
    latitude: 34.1565,
    longitude: -118.3583,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f01a', place_id: 'csh-01', content: 'Davidson designed three Case Study Houses — more than any other architect in the program.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-02',
    collection_id: 'col-csh',
    name: 'CSH #2 — Spaulding & Rex',
    description: 'A courtyard house organized around outdoor living — one of the earliest Case Study Houses built. Demonstrates the California ideal of seamless indoor-outdoor flow.',
    architect: 'Sumner Spaulding and John Rex',
    year_built: 1947,
    category: 'residential',
    latitude: 34.1323,
    longitude: -118.0826,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f02a', place_id: 'csh-02', content: 'The program was launched by Arts & Architecture magazine editor John Entenza in January 1945.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-03',
    collection_id: 'col-csh',
    name: 'CSH #3 — Wurster & Bernardi',
    description: 'The only Northern California–designed CSH built in Los Angeles. Took a more informal ranch house approach to modernism. Demolished in 2013.',
    architect: 'William W. Wurster and Theodore Bernardi',
    year_built: 1950,
    category: 'residential',
    latitude: 34.0788,
    longitude: -118.5027,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f03a', place_id: 'csh-03', content: 'Demolished in 2013 after decades of neglect — one of several Case Study Houses lost to development.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-07',
    collection_id: 'col-csh',
    name: 'CSH #7 — Abell',
    description: 'A modest post-and-beam house in San Gabriel by Thornton Abell, demonstrating the program\'s commitment to affordable modern design for the average American family.',
    architect: 'Thornton Abell',
    year_built: 1948,
    category: 'residential',
    latitude: 34.1052,
    longitude: -118.1023,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f07a', place_id: 'csh-07', content: 'The Case Study Houses were published in Arts & Architecture magazine, reaching over 100,000 monthly readers.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-08',
    collection_id: 'col-csh',
    name: 'CSH #8 — Eames House',
    description: 'Perhaps the most celebrated Case Study House. Charles and Ray Eames designed it as their own home — a steel-frame structure assembled entirely from off-the-shelf industrial catalogue components in Pacific Palisades.',
    architect: 'Charles and Ray Eames',
    year_built: 1949,
    category: 'residential',
    latitude: 34.0300,
    longitude: -118.5194,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f08a', place_id: 'csh-08', content: 'The entire steel structure was erected in just 16 hours using off-the-shelf industrial components ordered from catalogues.', order_index: 0 },
      { id: 'csh-f08b', place_id: 'csh-08', content: 'Declared a National Historic Landmark in 2006. Now managed by the Eames Foundation.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: 'csh-09',
    collection_id: 'col-csh',
    name: 'CSH #9 — Entenza House',
    description: 'Designed as the personal residence of Arts & Architecture editor John Entenza — the program\'s founder and patron — directly adjacent to the Eames House in Pacific Palisades.',
    architect: 'Charles Eames and Eero Saarinen',
    year_built: 1950,
    category: 'residential',
    latitude: 34.0301,
    longitude: -118.5188,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f09a', place_id: 'csh-09', content: 'Eames and Saarinen originally designed one unified scheme for both houses; the designs were later separated.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-10',
    collection_id: 'col-csh',
    name: 'CSH #10 — Nomland',
    description: 'A Pasadena hillside house by father-and-son architects Kemper Nomland Sr. and Jr., featuring exposed post-and-beam structure and floor-to-ceiling glazing.',
    architect: 'Kemper Nomland and Kemper Nomland Jr.',
    year_built: 1947,
    category: 'residential',
    latitude: 34.1312,
    longitude: -118.1703,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f10a', place_id: 'csh-10', content: 'One of the few Case Study Houses designed by a father-and-son team.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-15',
    collection_id: 'col-csh',
    name: 'CSH #15 — Davidson',
    description: 'A compact hillside residence in La Cañada Flintridge by Julius Ralph Davidson, one of the Case Study program\'s most prolific contributors.',
    architect: 'Julius Ralph Davidson',
    year_built: 1947,
    category: 'residential',
    latitude: 34.2123,
    longitude: -118.2075,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f15a', place_id: 'csh-15', content: 'Davidson\'s three Case Study Houses (1, 11, 15) each explored different approaches to the compact modern home.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-16',
    collection_id: 'col-csh',
    name: 'CSH #16 — Walker',
    description: 'A demonstration house in Beverly Hills by Rodney Walker, emphasizing prefabricated elements and modular planning. Demolished around 2004.',
    architect: 'Rodney Walker',
    year_built: 1947,
    category: 'residential',
    latitude: 34.0957,
    longitude: -118.4259,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f16a', place_id: 'csh-16', content: 'Demolished around 2004. Walker designed three Case Study Houses (16, 17, 18), all in the postwar Los Angeles suburbs.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-17',
    collection_id: 'col-csh',
    name: 'CSH #17 — Ellwood',
    description: 'Craig Ellwood\'s first Case Study House — a refined steel-and-glass pavilion in Beverly Hills. Heavily altered since original construction.',
    architect: 'Craig Ellwood',
    year_built: 1956,
    category: 'residential',
    latitude: 34.1213,
    longitude: -118.4032,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f17a', place_id: 'csh-17', content: 'Ellwood had no formal architecture degree — he studied structural engineering at UCLA while working for other firms.', order_index: 0 },
      { id: 'csh-f17b', place_id: 'csh-17', content: 'Heavily altered from its original configuration; only the steel frame and basic volume survive.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: 'csh-18',
    collection_id: 'col-csh',
    name: 'CSH #18 — Walker',
    description: 'Perched on the Pacific Palisades bluffs with sweeping ocean views, this post-and-beam house by Rodney Walker is one of the program\'s finest surviving examples.',
    architect: 'Rodney Walker',
    year_built: 1947,
    category: 'residential',
    latitude: 34.0298,
    longitude: -118.5193,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f18a', place_id: 'csh-18', content: 'Located steps from the Eames House (CSH#8), the two together formed a remarkable cluster of modernist experimentation in Pacific Palisades.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-20',
    collection_id: 'col-csh',
    name: 'CSH #20 — Bass House',
    description: 'The home of legendary graphic designer Saul Bass, designed with characteristic wood post-and-beam construction by Buff, Straub & Hensman in Altadena.',
    architect: 'Buff, Straub and Hensman',
    year_built: 1958,
    category: 'residential',
    latitude: 34.1985,
    longitude: -118.1342,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f20a', place_id: 'csh-20', content: 'Saul Bass, who lived here, designed some of the most iconic film title sequences and logos of the 20th century.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-21',
    collection_id: 'col-csh',
    name: 'CSH #21 — Bailey House',
    description: 'Pierre Koenig\'s first Case Study House — a flat-roofed steel-frame pavilion in Laurel Canyon that established his signature minimalist vocabulary.',
    architect: 'Pierre Koenig',
    year_built: 1958,
    category: 'residential',
    latitude: 34.1166,
    longitude: -118.3917,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f21a', place_id: 'csh-21', content: 'Designated Los Angeles Historic-Cultural Monument #669.', order_index: 0 },
      { id: 'csh-f21b', place_id: 'csh-21', content: 'Koenig\'s steel-frame approach was a direct response to the postwar availability of surplus industrial materials.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: 'csh-22',
    collection_id: 'col-csh',
    name: 'CSH #22 — Stahl House',
    description: 'The most iconic Case Study House, immortalized in Julius Shulman\'s 1960 photograph. An all-steel pavilion cantilevered over the Hollywood Hills with breathtaking panoramic city views.',
    architect: 'Pierre Koenig',
    year_built: 1960,
    category: 'residential',
    latitude: 34.1002,
    longitude: -118.3687,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f22a', place_id: 'csh-22', content: 'Julius Shulman\'s 1960 photograph of two women seated inside the glass pavilion above the city lights became one of the most reproduced architectural images ever taken.', order_index: 0 },
      { id: 'csh-f22b', place_id: 'csh-22', content: 'The L-shaped plan wraps two sides of the hilltop site, with floor-to-ceiling glass exposing 270° views of Los Angeles.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: 'csh-23',
    collection_id: 'col-csh',
    name: 'CSH #23 — TRIAD',
    description: 'Three adjacent courtyard apartments in La Jolla demonstrating that Case Study principles — economy, prefabrication, steel structure — could be applied to multi-family housing.',
    architect: 'Killingsworth, Brady and Smith',
    year_built: 1960,
    category: 'residential',
    latitude: 32.8434,
    longitude: -117.2532,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f23a', place_id: 'csh-23', content: 'The only Case Study project comprising three separate but identical houses on adjacent lots — exploring the idea of the modernist residential cluster.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-25',
    collection_id: 'col-csh',
    name: 'CSH #25 — Frank House',
    description: 'A Long Beach canal house renowned for its celebrated 17-foot folding door that entirely dissolves the boundary between the living room and the private canal terrace.',
    architect: 'Killingsworth, Brady, Smith and Associates',
    year_built: 1962,
    category: 'residential',
    latitude: 33.7554,
    longitude: -118.1241,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f25a', place_id: 'csh-25', content: 'Sited on the Naples Island canal system in Long Beach, the house mediates between the public street and the private waterway.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-26',
    collection_id: 'col-csh',
    name: 'CSH #26 — Harrison House',
    description: 'The only Case Study House built in Northern California, located in the Peacock Gap neighborhood of San Rafael. A quiet wood-and-glass pavilion set against a suburban hillside.',
    architect: 'Beverley David Thorne',
    year_built: 1962,
    category: 'residential',
    latitude: 37.9729,
    longitude: -122.5189,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f26a', place_id: 'csh-26', content: 'The northernmost Case Study House — the only one outside Southern California.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-28',
    collection_id: 'col-csh',
    name: 'CSH #28 — Buff & Hensman',
    description: 'The final realized Case Study House, a refined wood post-and-beam design in Thousand Oaks — closing the 21-year program with characteristic Southern California understatement.',
    architect: 'Conrad Buff and Donald Hensman',
    year_built: 1966,
    category: 'residential',
    latitude: 34.1689,
    longitude: -118.8799,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f28a', place_id: 'csh-28', content: 'CSH#28 was the last of 36 houses commissioned; only 25 were ever built.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: 'csh-1950',
    collection_id: 'col-csh',
    name: 'CSH 1950 — Soriano',
    description: 'The first all-steel Case Study House, designed by Raphael Soriano in Pacific Palisades. A precise, column-free steel pavilion that won the AIA Award of Merit in 1951.',
    architect: 'Raphael Soriano',
    year_built: 1950,
    category: 'residential',
    latitude: 34.0488,
    longitude: -118.5086,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-f1950a', place_id: 'csh-1950', content: 'First fully steel-framed house in the program, predating Eames\'s and Ellwood\'s steel work.', order_index: 0 },
      { id: 'csh-f1950b', place_id: 'csh-1950', content: 'Won the AIA Award of Merit in 1951 for its economy, structural clarity, and livability.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: 'csh-az',
    collection_id: 'col-csh',
    name: 'CSH #1 Arizona — Beadle',
    description: 'The only Arts & Architecture Case Study project built outside California — a three-unit apartment complex in Phoenix\'s Biltmore neighborhood, demonstrating urban modernism in the desert Southwest.',
    architect: 'Alfred N. Beadle and Alan A. Dailey',
    year_built: 1961,
    category: 'residential',
    latitude: 33.5034,
    longitude: -112.0197,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-csh', city: 'Los Angeles', country: 'United States', name: 'Case Study Houses', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'csh-faza', place_id: 'csh-az', content: 'The only Case Study project built outside California — proof the program\'s ideas could apply nationwide.', order_index: 0 },
    ],
    images: [],
  },
]
