import type { Place, Collection } from '@/types'

export const MOCK_COLLECTIONS: Collection[] = [
  { id: 'col-sp', name: 'São Paulo', city: 'São Paulo', country: 'Brazil', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-rome', name: 'Rome', city: 'Rome', country: 'Italy', description: null, cover_image_url: null, price_brl: 29.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-paris', name: 'Paris', city: 'Paris', country: 'France', description: null, cover_image_url: null, price_brl: 24.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-sydney', name: 'Sydney', city: 'Sydney', country: 'Australia', description: null, cover_image_url: null, price_brl: 19.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
  { id: 'col-tokyo', name: 'Japan', city: 'Osaka', country: 'Japan', description: null, cover_image_url: null, price_brl: 34.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
]

export const MOCK_PLACES: Place[] = [
  {
    id: '1',
    collection_id: 'col-rome',
    name: 'Colosseum',
    description: 'The largest amphitheater ever built, symbol of the Roman Empire. With a capacity of up to 80,000 spectators, it hosted gladiatorial contests and public spectacles for centuries.',
    architect: 'Vespasian / Titus',
    year_built: 80,
    category: 'public',
    latitude: 41.8902,
    longitude: 12.4922,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-rome', city: 'Rome', country: 'Italy', name: 'Rome', description: null, cover_image_url: null, price_brl: 29.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f1', place_id: '1', content: 'It took only 8 years to build.', order_index: 0 },
      { id: 'f2', place_id: '1', content: 'It had a retractable awning system (velarium) to protect spectators from the sun.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: '2',
    collection_id: 'col-paris',
    name: 'Centre Pompidou',
    description: 'Modern art museum with an exposed high-tech structure. Winner of an international competition in 1977, it turned inside-out architecture into a public statement.',
    architect: 'Renzo Piano & Richard Rogers',
    year_built: 1977,
    category: 'museum',
    latitude: 48.8606,
    longitude: 2.3522,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-paris', city: 'Paris', country: 'France', name: 'Paris', description: null, cover_image_url: null, price_brl: 24.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f3', place_id: '2', content: 'All structural and mechanical systems are exposed and color-coded by function.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: '3',
    collection_id: 'col-sp',
    name: 'MASP',
    description: 'Museu de Arte de São Paulo Assis Chateaubriand. Designed by Lina Bo Bardi and suspended by four red pillars over a single 74-meter free span.',
    architect: 'Lina Bo Bardi',
    year_built: 1968,
    category: 'museum',
    latitude: -23.5614,
    longitude: -46.6558,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-sp', city: 'São Paulo', country: 'Brazil', name: 'São Paulo', description: null, cover_image_url: null, price_brl: 0, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f4', place_id: '3', content: 'The 74m free span is one of the largest in the world for a structure of its era.', order_index: 0 },
      { id: 'f5', place_id: '3', content: 'Lina Bo Bardi wanted Avenida Paulista to be "crossed through" the museum beneath it.', order_index: 1 },
    ],
    images: [],
  },
  {
    id: '4',
    collection_id: 'col-sydney',
    name: 'Sydney Opera House',
    description: 'Icon of 20th-century architecture with interlocking concrete shell vaults in the shape of sails. UNESCO World Heritage Site since 2007.',
    architect: 'Jørn Utzon',
    year_built: 1973,
    category: 'public',
    latitude: -33.8568,
    longitude: 151.2153,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-sydney', city: 'Sydney', country: 'Australia', name: 'Sydney', description: null, cover_image_url: null, price_brl: 19.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f6', place_id: '4', content: 'The project was selected in 1957 from a competition with 233 entries.', order_index: 0 },
    ],
    images: [],
  },
  {
    id: '5',
    collection_id: 'col-tokyo',
    name: 'Church of the Light',
    description: 'A cross-shaped slit of light cut into a concrete wall — one of the most powerful architectural moments of the 20th century.',
    architect: 'Tadao Ando',
    year_built: 1989,
    category: 'religious',
    latitude: 34.5913,
    longitude: 135.4803,
    cover_image_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    collection: { id: 'col-tokyo', city: 'Osaka', country: 'Japan', name: 'Japan', description: null, cover_image_url: null, price_brl: 34.9, stripe_price_id: null, is_published: true, created_at: new Date().toISOString() },
    facts: [
      { id: 'f7', place_id: '5', content: 'Tadao Ando is self-taught — he never attended an architecture school.', order_index: 0 },
    ],
    images: [],
  },
]
